/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pratofiorito;

import java.awt.BorderLayout;
import javax.swing.JComboBox;

/**
 *
 * @author orsenigo_giacomo
 */
public class NewJFrame extends javax.swing.JFrame {
    
    private tabella pannelloGioco = new tabella();

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        setTitle("ciaoooo");
        setTitle("Campo minatoooo");
        initComponents();
        
        getContentPane().add(jPanel1, BorderLayout.PAGE_START);
        getContentPane().add(pannelloGioco, BorderLayout.CENTER);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        textFieldRighe = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textFieldColonne = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textFieldBombe = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        jLabel4.setText("Modalità:");
        jPanel1.add(jLabel4);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Facile", "Medio", "Difficile", "Personalizzato" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);

        jLabel1.setText("Righe:");
        jPanel1.add(jLabel1);

        textFieldRighe.setText("9");
        textFieldRighe.setToolTipText("");
        textFieldRighe.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel1.add(textFieldRighe);

        jLabel2.setText("Colonne:");
        jPanel1.add(jLabel2);

        textFieldColonne.setText("9");
        textFieldColonne.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel1.add(textFieldColonne);

        jLabel3.setText("Bombe:");
        jPanel1.add(jLabel3);

        textFieldBombe.setText("10");
        textFieldBombe.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel1.add(textFieldBombe);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        pannelloGioco.change(Integer.parseInt(textFieldRighe.getText()), Integer.parseInt(textFieldColonne.getText()), Integer.parseInt(textFieldBombe.getText()));
        pack();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        JComboBox cb = (JComboBox) evt.getSource();
        switch (cb.getSelectedIndex()) {
            case 0:
                textFieldRighe.setText("9");
                textFieldColonne.setText("9");
                textFieldBombe.setText("10");
                break;
            case 1:
                textFieldRighe.setText("16");
                textFieldColonne.setText("16");
                textFieldBombe.setText("40");
                break;
            case 2:
                
                textFieldRighe.setText("16");
                textFieldColonne.setText("30");
                textFieldBombe.setText("99");
                break;
            case 3:
                break;
            default:
                break;
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized

        // TODO add your handling code here:
        System.out.println("ridimensionato!!!!!!");
        System.out.println(pannelloGioco.getLayout().preferredLayoutSize(this).toString());
        System.out.println("frame: " + getWidth() + "," + getHeight());
        System.out.println("panel2: " + pannelloGioco.getWidth() + "," + pannelloGioco.getHeight());
    }//GEN-LAST:event_formComponentResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textFieldBombe;
    private javax.swing.JTextField textFieldColonne;
    private javax.swing.JTextField textFieldRighe;
    // End of variables declaration//GEN-END:variables

}
